namespace SnapLingoWindows.Services;

public sealed class LocalizationService
{
    private readonly IReadOnlyDictionary<string, string> english;
    private readonly IReadOnlyDictionary<string, string> chinese;

    public LocalizationService(AppLanguage language)
    {
        english = BuildEnglish();
        chinese = BuildChinese();
        CurrentLanguage = language;
    }

    public event EventHandler? LanguageChanged;

    public AppLanguage CurrentLanguage { get; private set; }

    public void SetLanguage(AppLanguage language)
    {
        if (CurrentLanguage == language)
        {
            return;
        }

        CurrentLanguage = language;
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Get(string key)
    {
        var table = CurrentLanguage == AppLanguage.Chinese ? chinese : english;
        return table.TryGetValue(key, out var value) ? value : key;
    }

    public string Format(string key, params object[] args) => string.Format(Get(key), args);

    private static IReadOnlyDictionary<string, string> BuildEnglish() => new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["window_settings_title"] = "SnapLingo Settings",
        ["window_panel_title"] = "SnapLingo Panel",
        ["sidebar_settings_title"] = "Settings Center",
        ["sidebar_sections"] = "SECTIONS",
        ["nav_basic"] = "Basic",
        ["nav_provider"] = "Provider",
        ["nav_prompt"] = "Prompt",
        ["nav_appearance"] = "Appearance",
        ["basic_title"] = "Basic",
        ["basic_hint"] = "Manage launch behavior and the global hotkey without leaving the main configuration flow.",
        ["provider_title"] = "Provider",
        ["provider_hint"] = "Connect a provider, pick the active model, and refresh the list from its API after saving your key.",
        ["prompt_title"] = "Prompt",
        ["prompt_hint"] = "Switch between prompt profiles or create your own prompt set for translate and polish actions.",
        ["appearance_title"] = "Appearance",
        ["appearance_hint"] = "Choose the interface language. Changes apply immediately without restarting SnapLingo.",
        ["label_provider"] = "Provider",
        ["label_hotkey"] = "Hotkey",
        ["label_storage"] = "Storage",
        ["label_workflow"] = "Workflow",
        ["storage_secure_local"] = "Secure local",
        ["workflow_selection_hotkey"] = "Selection + hotkey",
        ["workflow_ready"] = "Ready",
        ["workflow_active"] = "Active",
        ["quick_actions"] = "Quick action mode",
        ["button_show_panel"] = "Show panel",
        ["button_use_clipboard"] = "Clipboard only",
        ["hotkey_hint"] = "Choose the shortcut that opens the translation panel from anywhere in Windows.",
        ["label_model"] = "Model",
        ["label_api_key"] = "API key",
        ["button_save_key"] = "Save key",
        ["button_clear_key"] = "Clear key",
        ["placeholder_load_models"] = "Save an API key to load models",
        ["loading_models"] = "Loading models...",
        ["prompt_profile"] = "Prompt profile",
        ["button_new"] = "New",
        ["button_save"] = "Save",
        ["button_delete"] = "Delete",
        ["label_name"] = "Name",
        ["label_translate_prompt"] = "Translate prompt",
        ["label_polish_prompt"] = "Polish prompt",
        ["label_language"] = "Language",
        ["language_english"] = "English",
        ["language_chinese"] = "中文",
        ["prompt_default_name"] = "Default",
        ["mode_translate"] = "Translate",
        ["mode_polish"] = "Polish",
        ["clipboard_prompt"] = "Direct capture is not ready on Windows. Press Ctrl+C to continue.",
        ["original_text"] = "Original Text",
        ["button_copy"] = "Copy",
        ["button_copied"] = "Copied",
        ["button_retry"] = "Retry",
        ["source_auto"] = "Auto",
        ["source_clipboard"] = "Clipboard",
        ["source_manual"] = "Manual",
        ["state_ready_title"] = "Ready",
        ["state_ready_status"] = "Use the global hotkey or trigger the workflow from this window.",
        ["state_capturing_title"] = "Capturing Selection",
        ["state_capturing_status"] = "Waiting for selected text or a clipboard fallback.",
        ["state_clipboard_title"] = "Press Copy To Continue",
        ["state_clipboard_primary"] = "Windows preview currently uses clipboard fallback for selection capture.",
        ["state_clipboard_status"] = "Press Ctrl+C in the current app. SnapLingo will continue automatically as soon as the clipboard changes.",
        ["state_translate_title"] = "Quick Translation",
        ["state_translate_status"] = "Generating a send-ready translation.",
        ["state_polish_title"] = "Polished Version",
        ["state_polish_status"] = "Polishing your English.",
        ["state_partial_status"] = "Optimizing the result.",
        ["state_partial_kept_status"] = "Kept the quick translation because the final polish step did not finish.",
        ["state_error_title"] = "Could Not Finish",
        ["state_error_status"] = "Retry the flow or switch modes.",
        ["state_copied_status"] = "Copied",
        ["error_no_copied_text"] = "SnapLingo never received copied text. Press the hotkey again or use the current clipboard.",
        ["error_empty_clipboard"] = "The clipboard does not contain text yet. Copy some text first and try again.",
        ["status_switched_provider"] = "Switched to {0}.",
        ["status_saved_key_loading"] = "Saved {0} API key. Loading models...",
        ["status_removed_key"] = "Removed {0} API key from secure local storage.",
        ["status_using_model"] = "Using model {0}.",
        ["status_save_key_first"] = "Save an API key first, then SnapLingo can load models automatically.",
        ["status_loaded_models"] = "Loaded {0} models for {1}.",
        ["status_using_prompt"] = "Using prompt {0}.",
        ["status_created_prompt"] = "Created prompt {0}.",
        ["status_default_prompt_readonly"] = "Default prompt is read-only.",
        ["status_default_prompt_undeletable"] = "Default prompt cannot be deleted.",
        ["status_prompt_fields_required"] = "Name, translate prompt, and polish prompt are required.",
        ["status_saved_prompt"] = "Saved prompt {0}.",
        ["status_deleted_prompt"] = "Deleted prompt {0}.",
        ["status_hotkey_set"] = "Hotkey set to {0}.",
        ["error_hotkey_register"] = "Could not register {0}. Windows returned {1}. Try a different preset.",
        ["error_add_api_key"] = "Add an API key in Settings to use translation.",
        ["error_provider_empty_result"] = "The provider returned an empty result.",
        ["error_provider_untrusted_result"] = "The provider returned a result SnapLingo cannot trust.",
        ["error_provider_busy"] = "The provider is temporarily busy. SnapLingo retried, but the request still did not finish.",
        ["error_provider_http"] = "The provider request failed with HTTP {0}.",
        ["error_provider_malformed"] = "The provider response was malformed.",
        ["error_save_key_first_models"] = "Save an API key first, then SnapLingo can load models automatically.",
        ["error_fetch_models_http"] = "Could not load models from {0}. HTTP {1}.",
        ["error_fetch_models_endpoint"] = "{0} did not expose a model-list endpoint for this API key or base URL. SnapLingo kept the single preset model instead.",
        ["error_fetch_models_ark"] = "Volcengine Ark does not expose model listing through the runtime API key used by SnapLingo. Its official model-list APIs are control-plane APIs that use HMAC-signed credentials.",
        ["error_fetch_models_none"] = "No usable text models were returned by {0}.",
        ["error_models_malformed"] = "The provider model list response was malformed.",
        ["nav_advanced"] = "Advanced",
        ["advanced_title"] = "Advanced",
        ["advanced_hint"] = "Review storage, workflow, and language status for the current desktop setup.",
        ["sidebar_footer_status"] = "Stored securely on this device.",
        ["hotkey_banner_prefix"] = "Current hotkey is",
        ["hotkey_banner_hint"] = "Select text and press the hotkey to open the translation or polish panel.",
        ["status_api_key_saved"] = "Saved securely for the current provider.",
        ["status_api_key_missing"] = "No API key has been saved for the current provider.",
    };

    private static IReadOnlyDictionary<string, string> BuildChinese() => new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["window_settings_title"] = "SnapLingo 设置",
        ["window_panel_title"] = "SnapLingo 面板",
        ["sidebar_settings_title"] = "\u8BBE\u7F6E\u4E2D\u5FC3",
        ["sidebar_sections"] = "分区",
        ["nav_basic"] = "基础",
        ["nav_provider"] = "模型",
        ["nav_prompt"] = "提示词",
        ["nav_appearance"] = "外观",
        ["basic_title"] = "基础",
        ["basic_hint"] = "在同一个配置流程里管理启动方式和全局热键。",
        ["provider_title"] = "模型",
        ["provider_hint"] = "连接服务商、选择当前模型，并在保存 API key 后从接口刷新模型列表。",
        ["prompt_title"] = "提示词",
        ["prompt_hint"] = "切换提示词配置，或为翻译与润色创建自定义提示词集。",
        ["appearance_title"] = "外观",
        ["appearance_hint"] = "选择界面语言，切换后立即生效，不需要重启 SnapLingo。",
        ["label_provider"] = "服务商",
        ["label_hotkey"] = "热键",
        ["label_storage"] = "存储",
        ["label_workflow"] = "工作流",
        ["storage_secure_local"] = "本地安全存储",
        ["workflow_selection_hotkey"] = "划词 + 热键",
        ["workflow_ready"] = "就绪",
        ["workflow_active"] = "运行中",
        ["quick_actions"] = "\u5FEB\u6377\u64CD\u4F5C\u6A21\u5F0F",
        ["button_show_panel"] = "\u663E\u793A\u72EC\u7ACB\u9762\u677F",
        ["button_use_clipboard"] = "\u4EC5\u4F7F\u7528\u526A\u8D34\u677F",
        ["hotkey_hint"] = "选择可在 Windows 任意位置唤起翻译面板的快捷键。",
        ["label_model"] = "模型",
        ["label_api_key"] = "API key",
        ["button_save_key"] = "保存密钥",
        ["button_clear_key"] = "清除密钥",
        ["placeholder_load_models"] = "保存 API key 后自动加载模型列表",
        ["loading_models"] = "正在加载模型列表...",
        ["prompt_profile"] = "提示词配置",
        ["button_new"] = "新建",
        ["button_save"] = "保存",
        ["button_delete"] = "删除",
        ["label_name"] = "名称",
        ["label_translate_prompt"] = "翻译提示词",
        ["label_polish_prompt"] = "润色提示词",
        ["label_language"] = "语言",
        ["language_english"] = "English",
        ["language_chinese"] = "中文",
        ["prompt_default_name"] = "默认",
        ["mode_translate"] = "翻译",
        ["mode_polish"] = "润色",
        ["clipboard_prompt"] = "Windows 当前还未支持直接取词，请按 Ctrl+C 继续。",
        ["original_text"] = "原文",
        ["button_copy"] = "复制",
        ["button_copied"] = "已复制",
        ["button_retry"] = "重试",
        ["source_auto"] = "自动",
        ["source_clipboard"] = "剪贴板",
        ["source_manual"] = "手动",
        ["state_ready_title"] = "就绪",
        ["state_ready_status"] = "使用全局热键，或直接在当前窗口触发流程。",
        ["state_capturing_title"] = "正在获取选中文本",
        ["state_capturing_status"] = "等待选中文本，或回退到剪贴板方案。",
        ["state_clipboard_title"] = "请先复制后继续",
        ["state_clipboard_primary"] = "Windows 预览版当前使用剪贴板回退方案获取选中文本。",
        ["state_clipboard_status"] = "请在当前应用中按 Ctrl+C，SnapLingo 会在剪贴板变化后自动继续。",
        ["state_translate_title"] = "快速翻译",
        ["state_translate_status"] = "正在生成可直接发送的英文翻译。",
        ["state_polish_title"] = "润色结果",
        ["state_polish_status"] = "正在润色你的英文。",
        ["state_partial_status"] = "正在优化结果。",
        ["state_partial_kept_status"] = "已保留快速翻译，因为最终润色步骤未能完成。",
        ["state_error_title"] = "未能完成",
        ["state_error_status"] = "请重试流程，或切换模式后再试。",
        ["state_copied_status"] = "已复制",
        ["error_no_copied_text"] = "SnapLingo 没有接收到复制的文本。请再次按下热键，或直接使用当前剪贴板。",
        ["error_empty_clipboard"] = "剪贴板中还没有文本。请先复制一段内容再重试。",
        ["status_switched_provider"] = "已切换到 {0}。",
        ["status_saved_key_loading"] = "已保存 {0} API key，正在加载模型列表...",
        ["status_removed_key"] = "已从本地安全存储中移除 {0} API key。",
        ["status_using_model"] = "当前使用模型 {0}。",
        ["status_save_key_first"] = "请先保存 API key，SnapLingo 才能自动加载模型列表。",
        ["status_loaded_models"] = "已从 {1} 加载 {0} 个模型。",
        ["status_using_prompt"] = "当前使用提示词 {0}。",
        ["status_created_prompt"] = "已创建提示词 {0}。",
        ["status_default_prompt_readonly"] = "默认提示词为只读，不能修改。",
        ["status_default_prompt_undeletable"] = "默认提示词不能删除。",
        ["status_prompt_fields_required"] = "名称、翻译提示词和润色提示词都不能为空。",
        ["status_saved_prompt"] = "已保存提示词 {0}。",
        ["status_deleted_prompt"] = "已删除提示词 {0}。",
        ["status_hotkey_set"] = "热键已设置为 {0}。",
        ["error_hotkey_register"] = "无法注册 {0}，Windows 返回了错误码 {1}。请尝试其他快捷键。",
        ["error_add_api_key"] = "请先在设置中添加 API key，再使用翻译能力。",
        ["error_provider_empty_result"] = "模型返回了空结果。",
        ["error_provider_untrusted_result"] = "模型返回的结果不可信，SnapLingo 已拒绝使用。",
        ["error_provider_busy"] = "模型服务暂时繁忙。SnapLingo 已自动重试，但请求仍未完成。",
        ["error_provider_http"] = "模型请求失败，HTTP 状态码 {0}。",
        ["error_provider_malformed"] = "模型返回的数据格式不正确。",
        ["error_save_key_first_models"] = "请先保存 API key，SnapLingo 才能自动加载模型列表。",
        ["error_fetch_models_http"] = "无法从 {0} 加载模型列表，HTTP 状态码 {1}。",
        ["error_fetch_models_endpoint"] = "{0} 当前 API key 或 base URL 没有暴露模型列表接口，SnapLingo 已保留单个预设模型。",
        ["error_fetch_models_ark"] = "Volcengine Ark 当前使用的 runtime API key 不支持直接列出模型。官方模型列表接口属于 control-plane API，需要 HMAC 签名凭证。",
        ["error_fetch_models_none"] = "{0} 没有返回可用的文本模型。",
        ["error_models_malformed"] = "模型列表响应格式不正确。",
        ["nav_advanced"] = "\u9AD8\u7EA7",
        ["advanced_title"] = "\u9AD8\u7EA7\u8BBE\u7F6E",
        ["advanced_hint"] = "\u67E5\u770B\u5F53\u524D\u684C\u9762\u73AF\u5883\u4E0B\u7684\u5B58\u50A8\u3001\u5DE5\u4F5C\u6D41\u548C\u8BED\u8A00\u72B6\u6001\u3002",
        ["sidebar_footer_status"] = "\u5DF2\u5B89\u5168\u4FDD\u5B58\u5728\u6B64\u8BBE\u5907",
        ["hotkey_banner_prefix"] = "\u5F53\u524D\u70ED\u952E\u5DF2\u8BBE\u7F6E\u4E3A",
        ["hotkey_banner_hint"] = "\u9009\u4E2D\u6587\u672C\u540E\u6309\u4E0B\u6B64\u70ED\u952E\uff0c\u5373\u53EF\u5FEB\u901F\u5524\u51FA\u7FFB\u8BD1\u6216\u6DA6\u8272\u9762\u677F\u3002",
        ["status_api_key_saved"] = "\u5F53\u524D\u670D\u52A1\u5546\u7684 API key \u5DF2\u5B89\u5168\u4FDD\u5B58\u3002",
        ["status_api_key_missing"] = "\u5F53\u524D\u670D\u52A1\u5546\u8FD8\u6CA1\u6709\u4FDD\u5B58 API key\u3002",
    };
}
